# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zoetrope labs
email: enquiries@zoetrope.io
description: > # this means to ignore newlines until "baseurl:"
  ZConnect is an end-to-end solution for connecting new or existing products
  to the web to unlock predictive maintenance, product intelligence and new business models.
  We provide expertise, and the tools to get your business making the most of IoT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zoetrope.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zoetropeLabs
github_username:  ZoetropeLabs
linkedin_page: https://www.linkedin.com/company/zoetrope-limited
phone: "+0117 403 3796"

meta:
  address: >
    26B Oakfield road<br />
    Clifton<br />
    Bristol<br />
    BS8 2BZ<br />
    United Kingdom
  phone: "0117 403 3796"
  email: enquiries@zoetrope.io
  vat: "VAT registration: 173132825"
  company: "Company No: 08742496"
  notice: Zoetrope Ltd Trading as Zoetrope Labs

google_analytics: UA-45970762-4

hs_portal_id: "515796"

permalink: /title

collections:
  people:
    output: true
  tech_blog:
    output: true
  client_stories:
    output: true
    permalink: /client-story/:title/
  careers:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js
  - js
  - scss
  - icons
  - images
  - _site
  - .code-highlighter-cache
  - case-studies
  - whitepapers

authors:
  benhowes:
    name: Ben Howes
    img: /assets/img/team/benhowes.jpg
  richwebb:
    name: Richard Webb
    img: /assets/img/team/richardwebb.jpg

defaults:
  - scope:
      path: ''
    values:
      primary_menu: false
      secondary_menu: false
      title: "Set a title!"
      mobile_weight: 50
  - scope:
      path: ''
      type: posts
    values:
      permalink: "/posts/:title/"
  - scope:
      path: ''
      type: tech_blog
    values:
      layout: article
      author: benhowes
      sidebar: blog_sidebar.html
      comments: true
      header_background: '/assets/img/tech-blog/blog.jpg'
  - scope:
      path: ''
      type: careers
    values:
      layout: article
      sidebar: careers_sidebar.html
      header_background: "/assets/img/homepage.jpg"
  - scope:
      path: ''
      type: client_stories
    values:
      layout: article
      cta: Seen enough?
      cta_body: If you're looking to progress your IoT ambitions, have a chat today!
      cta_link: /contact
      cta_link_text: Let's talk
