# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zconnect
email: enquiries@zoetrope.io
description: > # this means to ignore newlines until "baseurl:"
  Zconnect is an end-to-end solution for connecting new or existing products
  to the web to unlock predictive maintenance, product intelligence and new business models.
  We provide expertise, and the tools to get your business making the most of IoT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zconnect.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
phone: "+441172300234"

meta:
  address: >
    26B Oakfield road<br />
    Clifton<br />
    Bristol<br />
    BS8 2BZ<br />
    United Kingdom
  phone: "T: 0117 230 0234"
  email: enquiries@zoetrope.io
  vat: "VAT registration: 173132825"
  company: "Company No: 08742496"
  notice: Zoetrope Ltd Trading as Zoetrope Labs

google_analytics: UA-45970762-5

hs_portal_id: "515796"

permalink: /title

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - gulpfile.js
  - js
  - scss
  - icons
  - images
  - _site
  - .code-highlighter-cache
  - case-studies
  - whitepapers


defults:
  -
    primary_menu: false
    secondary_menu: false
    title: "Set a title!"
